-- =========================================================
-- RUNTIME MOVEMENT RECONCILIATION PROFILE SEED
-- Authoritative source for the rich movement reconciliation profile sent by
-- game-server snapshots to Unreal.
-- =========================================================

INSERT INTO apeiron.runtime_movement_reconciliation_profile (
    profile_id,
    max_speed,
    sprint_speed_multiplier,
    acceleration,
    deceleration,
    ground_friction,
    air_acceleration,
    jump_height,
    jump_duration_ms,
    rotation_rate_yaw,
    gravity_scale,
    braking_friction_factor,
    max_slope_deg,
    step_height,
    base_deadzone,
    grounded_speed_deadzone_factor,
    grounded_speed_deadzone_min,
    grounded_speed_deadzone_max,
    grounded_transition_deadzone_min,
    move_sustain_deadzone,
    move_sustain_transition_deadzone,
    airborne_deadzone,
    leap_recent_deadzone,
    leap_airborne_snapshot_deadzone,
    leap_landing_deadzone_factor,
    leap_landing_deadzone_min,
    leap_landing_deadzone_max,
    leap_landing_clamp_ignore_deadzone,
    leap_landing_soft_snap_deadzone,
    dodge_recent_deadzone,
    dodge_active_deadzone,
    dodge_exit_deadzone_factor,
    dodge_exit_deadzone_min,
    dodge_exit_deadzone_max,
    post_action_grounded_deadzone,
    correction_max_step,
    hard_snap_distance,
    severe_desync_distance,
    visual_smoothing_ms,
    visual_smoothing_max_distance,
    remote_visual_interpolation_ms,
    remote_visual_max_extrapolation_ms,
    remote_visual_hard_snap_distance,
    dodge_carry_handoff_ms,
    leap_landing_correction_grace_ms,
    leap_grounded_carry_handoff_ms,
    movement_turn_resubmit_dot_threshold,
    movement_turn_resubmit_min_interval_ms,
    movement_submit_interval_ms,
    snapshot_poll_interval_ms,
    strafe_speed_multiplier,
    backpedal_speed_multiplier,
    strafe_sprint_speed_multiplier,
    backpedal_sprint_speed_multiplier,
    metadata
)
VALUES (
    'player_default_movement_profile',
    470,
    1.45,
    2048,
    2048,
    8,
    768,
    180,
    620,
    720,
    1,
    2,
    45,
    45,
    25,
    0.08,
    35,
    90,
    34,
    45,
    65,
    120,
    140,
    165,
    0.12,
    80,
    180,
    145,
    145,
    90,
    90,
    0.12,
    65,
    180,
    55,
    80,
    1400,
    2200,
    80,
    260,
    100,
    100,
    600,
    120,
    120,
    70,
    0.92,
    33,
    33,
    33,
    0.92,
    0.65,
    0.75,
    0.75,
    '{"source":"canonical_bootstrap","authority":"db","notes":"Canonical shared movement profile for server-authoritative movement."}'::jsonb
)
ON CONFLICT (profile_id) DO UPDATE SET
    max_speed = EXCLUDED.max_speed,
    sprint_speed_multiplier = EXCLUDED.sprint_speed_multiplier,
    acceleration = EXCLUDED.acceleration,
    deceleration = EXCLUDED.deceleration,
    ground_friction = EXCLUDED.ground_friction,
    air_acceleration = EXCLUDED.air_acceleration,
    jump_height = EXCLUDED.jump_height,
    jump_duration_ms = EXCLUDED.jump_duration_ms,
    rotation_rate_yaw = EXCLUDED.rotation_rate_yaw,
    gravity_scale = EXCLUDED.gravity_scale,
    braking_friction_factor = EXCLUDED.braking_friction_factor,
    max_slope_deg = EXCLUDED.max_slope_deg,
    step_height = EXCLUDED.step_height,
    base_deadzone = EXCLUDED.base_deadzone,
    grounded_speed_deadzone_factor = EXCLUDED.grounded_speed_deadzone_factor,
    grounded_speed_deadzone_min = EXCLUDED.grounded_speed_deadzone_min,
    grounded_speed_deadzone_max = EXCLUDED.grounded_speed_deadzone_max,
    grounded_transition_deadzone_min = EXCLUDED.grounded_transition_deadzone_min,
    move_sustain_deadzone = EXCLUDED.move_sustain_deadzone,
    move_sustain_transition_deadzone = EXCLUDED.move_sustain_transition_deadzone,
    airborne_deadzone = EXCLUDED.airborne_deadzone,
    leap_recent_deadzone = EXCLUDED.leap_recent_deadzone,
    leap_airborne_snapshot_deadzone = EXCLUDED.leap_airborne_snapshot_deadzone,
    leap_landing_deadzone_factor = EXCLUDED.leap_landing_deadzone_factor,
    leap_landing_deadzone_min = EXCLUDED.leap_landing_deadzone_min,
    leap_landing_deadzone_max = EXCLUDED.leap_landing_deadzone_max,
    leap_landing_clamp_ignore_deadzone = EXCLUDED.leap_landing_clamp_ignore_deadzone,
    leap_landing_soft_snap_deadzone = EXCLUDED.leap_landing_soft_snap_deadzone,
    dodge_recent_deadzone = EXCLUDED.dodge_recent_deadzone,
    dodge_active_deadzone = EXCLUDED.dodge_active_deadzone,
    dodge_exit_deadzone_factor = EXCLUDED.dodge_exit_deadzone_factor,
    dodge_exit_deadzone_min = EXCLUDED.dodge_exit_deadzone_min,
    dodge_exit_deadzone_max = EXCLUDED.dodge_exit_deadzone_max,
    post_action_grounded_deadzone = EXCLUDED.post_action_grounded_deadzone,
    correction_max_step = EXCLUDED.correction_max_step,
    hard_snap_distance = EXCLUDED.hard_snap_distance,
    severe_desync_distance = EXCLUDED.severe_desync_distance,
    visual_smoothing_ms = EXCLUDED.visual_smoothing_ms,
    visual_smoothing_max_distance = EXCLUDED.visual_smoothing_max_distance,
    remote_visual_interpolation_ms = EXCLUDED.remote_visual_interpolation_ms,
    remote_visual_max_extrapolation_ms = EXCLUDED.remote_visual_max_extrapolation_ms,
    remote_visual_hard_snap_distance = EXCLUDED.remote_visual_hard_snap_distance,
    dodge_carry_handoff_ms = EXCLUDED.dodge_carry_handoff_ms,
    leap_landing_correction_grace_ms = EXCLUDED.leap_landing_correction_grace_ms,
    leap_grounded_carry_handoff_ms = EXCLUDED.leap_grounded_carry_handoff_ms,
    movement_turn_resubmit_dot_threshold = EXCLUDED.movement_turn_resubmit_dot_threshold,
    movement_turn_resubmit_min_interval_ms = EXCLUDED.movement_turn_resubmit_min_interval_ms,
    movement_submit_interval_ms = EXCLUDED.movement_submit_interval_ms,
    snapshot_poll_interval_ms = EXCLUDED.snapshot_poll_interval_ms,
    strafe_speed_multiplier = EXCLUDED.strafe_speed_multiplier,
    backpedal_speed_multiplier = EXCLUDED.backpedal_speed_multiplier,
    strafe_sprint_speed_multiplier = EXCLUDED.strafe_sprint_speed_multiplier,
    backpedal_sprint_speed_multiplier = EXCLUDED.backpedal_sprint_speed_multiplier,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
